# Generated by Django 4.2.1 on 2024-06-06 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, null=True, verbose_name='Название')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('choice', models.CharField(choices=[('Google', 'Google'), ('Yandex', 'Yandex'), ('Dropbox', 'Dropbox'), ('GOOGLE_DISK', 'Google Диск'), ('YANDEX_DISK', 'Yandex Диск'), ('MAIL_CLOUD', 'Облако Mail'), ('SBERDISK', 'Сбердиск'), ('Telegram', 'Telegram'), ('VK', 'VK')], max_length=50)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ссылки')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['time_create'], name='links_links_time_cr_3a8a69_idx')],
            },
        ),
    ]
