# Generated by Django 4.2.1 on 2024-06-06 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название обсуждения')),
                ('description', models.TextField(blank=True, verbose_name='Описание обсуждения')),
                ('status', models.IntegerField(choices=[(0, 'Закрыто'), (1, 'Открыто')], default=1)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания обсуждения')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления обсуждения')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.discussions')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='social.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='discussions',
            index=models.Index(fields=['time_create'], name='social_disc_time_cr_b0540f_idx'),
        ),
    ]
